In [1]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [2]:
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

In [3]:
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_counts)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])


In [4]:
print(token.document_count)

3


In [5]:
print(token.word_docs)

defaultdict(<class 'int'>, {'각': 1, '먼저': 1, '텍스트의': 2, '나누어': 1, '단어를': 1, '토큰화합니다': 1, '딥러닝에서': 2, '단어로': 1, '토큰화해야': 1, '인식됩니다': 1, '수': 1, '사용할': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1})


In [6]:
# 주어진 단어를 '단어'로 토큰화 하기
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리할 텍스트 정하기
text = '해보지 않으면 해낼 수 없다'

# 해당 텍스트 토큰화
result = text_to_word_sequence(text)
print('\n원문:\n', text)
print('\n토큰화:\n', result)

# 텍스트 전처리 함수 Tokenizer()호출
from keras.preprocessing.text import Tokenizer

# 전처리하려는 세 개의 문장 정하기
docs = ['먼저 텍스트의 각 단어를 나누어 토큰화 합니다.',
       '텍스트의 단어로 토큰화해야 딥러닝에서 인식됩니다.',
       '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.']

# 토큰화 함수를 이용해 전처리하는 과정
token = Tokenizer() # 토큰화 함수 지정
token.fit_on_texts(docs) # 토큰화 함수에 문장 적용

# 각 옵션에 맞춰 단어의 빈도 수를 계산한 결과를 출력
print('\n 단어 카운트 : \n', token.word_counts)

# 출력되는 순서는 랜덤
print('\n문장 카운트 : ', token.document_count)
print('\n각 단어가 몇 개의 문장에 포함되어 있는가:\n', token.word_docs)
print('\n각 단어에 매겨진 인덱스 값 : \n', token.word_index)


원문:
 해보지 않으면 해낼 수 없다

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']


Using TensorFlow backend.



 단어 카운트 : 
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 1), ('나누어', 1), ('토큰화', 1), ('합니다', 1), ('단어로', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트 :  3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'토큰화': 1, '각': 1, '합니다': 1, '먼저': 1, '텍스트의': 2, '나누어': 1, '단어를': 1, '딥러닝에서': 2, '단어로': 1, '토큰화해야': 1, '인식됩니다': 1, '수': 1, '사용할': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1})

각 단어에 매겨진 인덱스 값 : 
 {'텍스트의': 1, '딥러닝에서': 2, '먼저': 3, '각': 4, '단어를': 5, '나누어': 6, '토큰화': 7, '합니다': 8, '단어로': 9, '토큰화해야': 10, '인식됩니다': 11, '토큰화한': 12, '결과는': 13, '사용할': 14, '수': 15, '있습니다': 16}


In [8]:
from keras.models import Sequential
from keras.layers import Embedding

model = Sequential()
model.add(Embedding(16, 4))

In [13]:
import numpy as np

In [15]:
# 긍, 부정 
# 텍스트 리뷰 자료 지정
docs = ['너무  재밌네요', '최고에요', '참 잘 만든 영화에요', 
       '추천하고 싶은 영화입니다.', '한 번 더 보고 싶네요',
       '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']
classes = np.array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [16]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고': 14, '싶네요': 15, '글쎄요': 16, '별로에요': 17, '생각보다': 18, '지루하네요': 19, '연기가': 20, '어색해요': 21, '재미없어요': 22}


In [17]:
x = token.texts_to_sequences(docs)
print(x)

[[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14, 15], [16], [17], [18, 19], [20, 21], [22]]


In [19]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

padded_x = pad_sequences(x, 4) # 서로 다른 길이의 데이터를 4로 맞추기
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]


In [20]:
import numpy as np
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

In [21]:
# 텍스트 리뷰 자료 지정
docs = ['너무 재밌네요', '최고에요', '참 잘 만든 영화에요', '추천하고 싶은 영화입니다', '한 번 더 보고 싶네요', '글쎄요', '별로에요', '생각보다 지루하네요', '연기가 어색해요', '재미없어요']


In [22]:
# 긍정 리뷰는 1, 부정 리뷰는 0으로 클래스 지정
classes = array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [23]:
# 토큰화
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)

{'너무': 1, '재밌네요': 2, '최고에요': 3, '참': 4, '잘': 5, '만든': 6, '영화에요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한': 11, '번': 12, '더': 13, '보고': 14, '싶네요': 15, '글쎄요': 16, '별로에요': 17, '생각보다': 18, '지루하네요': 19, '연기가': 20, '어색해요': 21, '재미없어요': 22}


In [24]:
# 패딩 - 서로 다른 길이의 데이터를 4로 맞춤
padded_x = pad_sequences(x, 4)
"\n패딩 결과\n", print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]


('\n패딩 결과\n', None)

In [25]:
print(padded_x)

[[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [12 13 14 15]
 [ 0  0  0 16]
 [ 0  0  0 17]
 [ 0  0 18 19]
 [ 0  0 20 21]
 [ 0  0  0 22]]


In [26]:
# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index) + 1


In [28]:
# 단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과 출력
model = Sequential()
model.add(Embedding(word_size, 8, input_length = 4))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])
model.fit(padded_x, classes , epochs = 20)

print('\n Accuracy : %.4f' %(model.evaluate(padded_x, classes)[1]))

Train on 10 samples
Epoch 1/20
10/10 [==============================] - 0s 44ms/sample - loss: 0.6939 - accuracy: 0.5000
Epoch 2/20
10/10 [==============================] - 0s 300us/sample - loss: 0.6918 - accuracy: 0.5000
Epoch 3/20
10/10 [==============================] - 0s 399us/sample - loss: 0.6896 - accuracy: 0.6000
Epoch 4/20
10/10 [==============================] - 0s 200us/sample - loss: 0.6875 - accuracy: 0.6000
Epoch 5/20
10/10 [==============================] - 0s 300us/sample - loss: 0.6853 - accuracy: 0.6000
Epoch 6/20
10/10 [==============================] - 0s 200us/sample - loss: 0.6832 - accuracy: 0.6000
Epoch 7/20
10/10 [==============================] - 0s 300us/sample - loss: 0.6810 - accuracy: 0.6000
Epoch 8/20
10/10 [==============================] - 0s 300us/sample - loss: 0.6789 - accuracy: 0.6000
Epoch 9/20
10/10 [==============================] - 0s 402us/sample - loss: 0.6768 - accuracy: 0.6000
Epoch 10/20
10/10 [==============================] - 0s 300us/s